/**
 * jMXPlayer, a GUI to IEEE PAR1599 (MX) data
 * Copyright © 2010 Riccardo Attilio Galli <riccardo@sideralis.org>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package src.View;

import javax.swing.JScrollPane;
import javax.swing.JPanel;
import org.jdesktop.layout.GroupLayout;
import javax.swing.WindowConstants;
import java.lang.reflect.Array;
import java.util.Hashtable;

import src.Component.VoicesPanel;
import src.Model.Voice;

/**
 *
 * @author Riquito
 */
public class VoicesWindow extends javax.swing.JFrame {
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JScrollPane scrollPanel;
	private JPanel voicesPanelContainer;
	// End of variables declaration//GEN-END:variables

	/** Creates new form VoicesWindow */
	public VoicesWindow() {
		initComponents();
	}

	/* Clean the window deleting/hiding present voices */
	public void cleanAll() {
		voicesPanelContainer.removeAll();
	}

	/* Insert the new voices in the window */
	public void populate(Hashtable<String, Voice> voicesDictionary) {
		((VoicesPanel) Array.get(this.voicesPanelContainer.getComponents(), 0)).populate(voicesDictionary);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// ">//GEN-BEGIN:initComponents
	private void initComponents() {
		scrollPanel = new JScrollPane();
		voicesPanelContainer = new JPanel();

		setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
		setTitle("Voci");
		GroupLayout voicesPanelContainerLayout = new GroupLayout(voicesPanelContainer);
		voicesPanelContainerLayout.setHorizontalGroup(
				voicesPanelContainerLayout.createParallelGroup(GroupLayout.LEADING).add(0, 742, Short.MAX_VALUE));
		voicesPanelContainerLayout.setVerticalGroup(
				voicesPanelContainerLayout.createParallelGroup(GroupLayout.LEADING).add(0, 453, Short.MAX_VALUE));
		scrollPanel.setViewportView(voicesPanelContainer);
		voicesPanelContainer.setLayout(voicesPanelContainerLayout);

		GroupLayout layout = new GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.LEADING).add(GroupLayout.TRAILING,
				layout.createSequentialGroup().addContainerGap()
						.add(scrollPanel, GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.LEADING).add(GroupLayout.TRAILING,
				layout.createSequentialGroup().addContainerGap()
						.add(scrollPanel, GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE).addContainerGap()));
		getContentPane().setLayout(layout);
		pack();
	}// </editor-fold>//GEN-END:initComponents
}
