/**
 * jMXPlayer, a GUI to IEEE PAR1599 (MX) data
 * Copyright © 2010 Riccardo Attilio Galli <riccardo@sideralis.org>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */



package mainFrame;

import java.awt.GridLayout;
import java.lang.reflect.Array;
import java.util.Hashtable;

/**
 *
 * @author  Riquito
 */
public class VoicesWindow extends javax.swing.JFrame {
    
    /** Creates new form VoicesWindow */
    public VoicesWindow() {
        initComponents();
        
        this.voicesPanelContainer.setLayout(new GridLayout(0,1));
        VoicesPanel testPanel=new VoicesPanel();
        
        this.voicesPanelContainer.add(testPanel);
        this.voicesPanelContainer.setVisible(true);
    }
    
    /*Clean the window deleting/hiding present voices*/
    public void cleanAll(){
        ((VoicesPanel)Array.get(this.voicesPanelContainer.getComponents(),0)).removeAllItems();
    }
    
    /*Insert the new voices in the window*/
    public void populate(Hashtable<String,Voice> voicesDict){
        ((VoicesPanel)Array.get(this.voicesPanelContainer.getComponents(),0)).populate(voicesDict);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane2 = new javax.swing.JScrollPane();
        voicesPanelContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Voci");
        org.jdesktop.layout.GroupLayout voicesPanelContainerLayout = new org.jdesktop.layout.GroupLayout(voicesPanelContainer);
        voicesPanelContainer.setLayout(voicesPanelContainerLayout);
        voicesPanelContainerLayout.setHorizontalGroup(
            voicesPanelContainerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 742, Short.MAX_VALUE)
        );
        voicesPanelContainerLayout.setVerticalGroup(
            voicesPanelContainerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 453, Short.MAX_VALUE)
        );
        jScrollPane2.setViewportView(voicesPanelContainer);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoicesWindow().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel voicesPanelContainer;
    // End of variables declaration//GEN-END:variables
    
}
